- NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

- Let's begin our introduction by exploring how to create NumPy arrays.

# Creating NumPy Arrays:

## Why you would want to use Arrays instead of lists

import numpy as np

- We can create an array by directly converting a list or list of lists:
- NumPy's arrays are more compact than Python lists -- a list of lists as you describe, in Python, would take at least 20 MB or so, while a NumPy 3D array with single-precision floats in the cells would fit in 4 MB. Access in reading and writing items is also faster with NumPy.

- Maybe you don't care that much for just a million cells, but you definitely would for a billion cells -- neither approach would fit in a 32-bit architecture, but with 64-bit builds NumPy would get away with 4 GB or so, Python alone would need at least about 12 GB (lots of pointers which double in size) -- a much costlier piece of hardware!

- The difference is mostly due to "indirectness" -- a Python list is an array of pointers to Python objects, at least 4 bytes per pointer plus 16 bytes for even the smallest Python object (4 for type pointer, 4 for reference count, 4 for value -- and the memory allocators rounds up to 16). A NumPy array is an array of uniform values -- single-precision numbers takes 4 bytes each, double-precision ones, 8 bytes. Less flexible, but you pay substantially for the flexibility of standard Python lists!

## From a Python list

In [10]:
import numpy as np

In [11]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [12]:
np.array(my_list)

array([1, 2, 3])

In [13]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix 

# matrix form

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrix)

# numpy array format

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built in Methods

- There are lots of built-in ways to generate arrays

## arrange

- Return evenly spaced values within a given interval

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 11, 3)

# starting from 0 ending with one less than 11 with 3 spaces between each numbers

array([0, 3, 6, 9])

## Zeros and Ones

- Generate arrays of zeros or ones

np.zeros(5)

In [18]:
np.zeros(17)

# np is in list

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace

- Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0, 20, 4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [22]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

- Creates an idnetity matrix and diagnoals are always 1 here

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(17)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0

Random

- Numpy also has lots of ways to create random number arrays:

## rand

- Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1]

In [26]:
np.random.rand(2)

array([0.65359608, 0.27551067])

In [27]:
np.random.rand(5, 5)

array([[0.54814599, 0.33229233, 0.84533132, 0.02451256, 0.43956304],
       [0.71563589, 0.73745878, 0.95258202, 0.68348388, 0.66712353],
       [0.62522656, 0.39949827, 0.29671358, 0.78902451, 0.08227546],
       [0.90709717, 0.40606237, 0.61388218, 0.13983973, 0.27502716],
       [0.82433907, 0.29183459, 0.48787081, 0.10238188, 0.61250203]])

## randn

- Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

In [28]:
np.random.randn(2)

array([0.09325743, 0.08015888])

In [29]:
np.random.randn(5, 5)

array([[ 0.1791116 , -0.32955959,  1.22749323, -0.67273215, -0.12703155],
       [-0.63795657, -1.84913345,  0.28912337,  0.38580028, -1.08895865],
       [-2.07435775,  1.39314909, -0.3904194 , -1.70385846, -0.45198296],
       [ 0.81923079,  2.20579428,  0.35725882, -0.91255085,  1.49810883],
       [-0.43807565, -1.0396987 , -1.06298611,  0.31790829, -0.74973504]])

## randint

- Return random integers from low(inclusive) to high(exclusive)

In [30]:
np.random.randint(1, 100)

42

In [31]:
np.random.randint(1, 100, 10)

# 1 inclusive, 100 exclusive with 10 numbers only

array([35, 30, 49, 78, 19, 37,  2, 84, 70,  6])

In [32]:
np.random.randint(1, 100, 100)


array([67,  9, 19, 22, 13, 24, 61, 30, 69,  8, 86, 42, 49, 67, 32, 48, 52,
       43, 86, 67, 75, 71, 60, 52, 79, 89, 55, 42, 29, 91,  2, 99, 18, 98,
       76, 68, 87, 82, 20, 66,  3, 25, 12, 39,  4, 23, 79, 70, 27, 90, 93,
       43, 51, 23, 18, 32,  4, 85, 54, 57, 59, 78, 89, 33, 37, 72, 69, 24,
       21, 38, 17, 13, 80, 63, 31, 79, 32, 70, 56, 26, 85, 33, 45, 29, 31,
       96, 16, 57, 25, 58, 38, 56,  3, 79, 60, 71, 74,  3,  6, 65])

## Array Attributes and Methods

- Let's discuss some useful attributes and methods or an array:

In [33]:
arr = np.arange(25)
ranArr = np.random.randint(0, 50, 10)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranArr

array([31, 37, 37, 15, 47, 46,  5,  8, 17, 26])

## Reshape

- Returns an array containing the same data with a new shape.

In [39]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## max, min, argmax, argmin

- These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [41]:
ranArr

array([31, 37, 37, 15, 47, 46,  5,  8, 17, 26])

In [42]:
ranArr.max()

47

In [43]:
ranArr.min()

5

In [44]:
ranArr.argmax()

# The argmax() function in NumPy is used to find the index of the maximum value in an array.

4

In [45]:
ranArr.argmin()

# The argmin() function in NumPy is used to find the index of the minimum value in an array.

6

## Shape

- Shape is an attribute that arrays have (not a method)

# Vector

In [46]:
arr.shape

(25,)

In [47]:
# Notice the two sets of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(1, 25).shape

(1, 25)

In [49]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [50]:
arr.reshape(25, 1).shape

(25, 1)

## dtype

- You can also grab the data type of the object in the array:
    

In [51]:
arr.dtype

dtype('int32')

# Great Job! Monisha Jain. Good Luck