## In this lec, we will discuss how to select elements or group of elements from an array

In [2]:
import numpy as np

In [3]:
# Creating sample array 

arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

- The simplest way to pick one or some elements of an array looks very similar to python lists:
    

In [5]:
# Get a value at an index

arr[9]

9

In [6]:
# Get values in a range

arr[1: 5]

# 1 inclusive and 5 exclusive

array([1, 2, 3, 4])

# Broadcasting

- NumPy arrays differ from a normal python list because of their ability to broadcast:

In [7]:
# Setting a value with index range (Broadcasting)

arr[0: 5] = 100

arr

# replaces values from 0 to 5 with a value 100

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array, we will see why I had to reset in a moment

arr = np.arange(0, 11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Important notes on Slices

In [10]:
slice_of_arr = arr[0: 6]

In [11]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
# change slice

slice_of_arr[:] = 99

# show slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

- Now note the changes also occur in our original array!

In [13]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Data is not copied, it's a view of the original array! This avoids memory problems!!!!

In [14]:
# To get a copy, neeed to be explicit

arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array(matrices)

- The general format is arr_2D[row][col] or arr_2D[row, col]. Suggest to using the comma notation for clarity

In [15]:
arr_2D = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
# Indexing row

In [16]:
arr_2D[1]

array([20, 25, 30])

In [18]:
# Format is arr_2D[row][col] or arr_2D[row, col]

In [19]:
# Getting individual element value

In [17]:
arr_2D[1, 0]

# or 

# arr_2D[1][0]

20

In [18]:
arr_2D[1][0]

20

In [20]:
# Getting individual element value

arr_2D[1][0]

20

In [21]:
arr_2D = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## 2D array slicing:
Shape (2, 2) from top right corner

In [24]:
arr_2D[:2, 1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr_2D[2]

array([35, 40, 45])

In [26]:
# Shape bottom row

In [27]:
arr_2D[2, :]

array([35, 40, 45])

## Fancy Indexing

- Fancy indexing allows you to select entire rows or columns out of order, to show this, let's quickly build out a numpy array:

In [28]:
# Set up matrix

In [29]:
arr_2D = np.zeros((10, 10))

In [30]:
# length of array

arr_length = arr_2D.shape[1]

In [31]:
# Set up array

for i in range(arr_length):
    arr_2D[i] = i
    
arr_2D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [32]:
# Fancy indexing allows the following:



In [33]:
arr_2D[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [34]:
# Allows in any order

In [35]:
arr_2D[[6, 4, 2, 7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More indexing help:

- Indexing a 2D matrix can be bit confusing at first, especially when you start to add in step size. 

## Selection

In [37]:
arr = np.arange(1, 11)

In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr > 4

In [42]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])