Now that we have learned about NumPy let's test ourselves. We will start off wit ha few simple tasks ans then we will be asked more complicated questions

In [1]:
import numpy as np


#### Import NumPy as np

In [2]:
import numpy as np

### Create an array of 10 zeros

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Create an array of 10 fives

In [5]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create an array of integers from 10 to 50

In [7]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create a 3 x 3 matrix with values ranging from 0 to 8

In [8]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a 3 x 3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Use NumPy to generate a random number between 0 and 1

In [11]:
np.random.rand(2)

array([0.16626245, 0.94060985])

In [12]:
np.random.rand(1)

array([0.95428321])

### Use NumPy to generata an array of 25 random numbers sampled from a standard normal distribution

In [13]:
np.random.randn(25)

array([-0.11502572, -0.41920189,  1.65746993,  1.55167819,  0.54179188,
       -0.24533744,  0.91635778, -1.44352218,  0.16166324,  0.88669267,
       -0.11771906,  0.2074883 , -0.4503987 ,  0.33996506, -0.95383879,
       -0.516346  ,  1.49614516,  0.43700041,  2.2443627 , -0.9282097 ,
        0.14290539,  0.37558669, -0.10896729, -2.2343898 ,  1.40517844])

### Create the following matrix:

### np.arange(1, 101).reshape(10, 10) / 100

In [14]:
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
np.arange(1, 101).reshape(10, 10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [16]:
np.arange(1, 101).reshape(10, 10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### Create an array of 20 linearly spaced points between 0 and 1

In [18]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### NumPy Indexing and Selection

- Now you will be gi ven a few matrices, and be asked to replicate the resulting matrix outputs

In [19]:
matrix = np.arange(1, 26).reshape(5, 5)

In [21]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
# to get the output from 
# 12, 13, 14, 15
# 17, 18, 19, 20
# 22, 23, 24, 25

matrix[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [23]:
# 20

In [24]:
matrix[3, 4]

20

In [25]:
matrix[3][4]

20

In [26]:
matrix[3:, 4]

array([20, 25])

In [27]:
# array([[ 2],
#       [ 7],
#       [12]])

In [28]:
matrix = np.arange(1, 26).reshape(5, 5)

In [29]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
matrix[: 3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
matrix[1:2]

array([[ 6,  7,  8,  9, 10]])

In [32]:
matrix[:3, 1: 2]

array([[ 2],
       [ 7],
       [12]])

In [33]:
matrix[4]

array([21, 22, 23, 24, 25])

In [34]:
matrix[:3][1:2]

array([[ 6,  7,  8,  9, 10]])

In [35]:
matrix[4, :]

array([21, 22, 23, 24, 25])

In [36]:
matrix[3: 5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

- Get the sum of all values in matrix

In [39]:
matrix.sum()

325

- Get the standard deviation of the values in matrix

In [40]:
matrix.std()

7.211102550927978

- Get the sum of all the columns in matrix

In [41]:
matrix.sum(axis = 0)

array([55, 60, 65, 70, 75])